packages:
  - packages/**
  - sites/**

allowBuilds:
  core-js: true
  esbuild: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - playwright-core@1.62.0
  - playwright@1.62.0

onlyBuiltDependencies:
  - core-js
  - esbuild
  - sharp
  - workerd
